AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Provisions infrastructure for the Node Demand Predictor
Resources:
    BucketJsonDatasource:
        Type: AWS::S3::Bucket
        Properties:
            VersioningConfiguration:
                Status: Enabled
            NotificationConfiguration:
                LambdaConfigurations:
                    -
                        Event: s3:ObjectCreated:*
                        Function: !GetAtt [LambdaCreateModel, Arn]
    LambdaCreateModel:
        Type: AWS::Lambda::Function
        Properties:
            Handler: handler.handler
            MemorySize: 128
            Role: !GetAtt [IamRoleLambdaCreateModel, Arn]
            Runtime: python2.7
            Timeout: 60
            Code: ./functions/create-model
    IamRoleLambdaCreateModel:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                        Service: lambda.amazonaws.com
                      Action: sts:AssumeRole
            Path: /
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    IamPolicyLambdaCreateModelRole1:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: read-from-s3
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: Allow
                        Action:
                            - s3:GetObject
                            - s3:PutObject
                        Resource:
                            - Fn::Join: [ "", [ !GetAtt [BucketJsonDatasource, Arn], "/*" ] ]
            Roles:
                - !Ref IamRoleLambdaCreateModel
    IamPolicyLambdaCreateModelRole2:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: create-ml-artifacts
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: Allow
                        Action:
                            - machinelearning:CreateDataSourceFromS3
                            - machinelearning:CreateMLModel
                            - machinelearning:CreateRealtimeEndpoint
                        Resource:
                            - Fn::Join: [ ":", [ "arn:aws:machinelearning", !Ref "AWS::Region", !Ref "AWS::AccountId", "*" ] ]
            Roles:
                - !Ref IamRoleLambdaCreateModel

    BucketJsonDatasourceLambdaInvokePermission:
        Type: AWS::Lambda::Permission
        Properties:
            FunctionName: !Ref LambdaCreateModel
            Action: lambda:InvokeFunction
            Principal: s3.amazonaws.com
            SourceAccount: !Ref AWS::AccountId
Outputs:
    OutputBucketName:
        Value: !Ref BucketJsonDatasource
